# Generated by Django 3.2.5 on 2021-07-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
