# Generated by Django 3.2.5 on 2021-07-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='Content',
            new_name='content',
        ),
    ]
