# Generated by Django 3.2.5 on 2021-07-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtool', '0001_initial'),
        ('idea', '0003_rename_content_idea_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devtool.devtool', verbose_name='예상 계발툴'),
        ),
    ]
