# Generated by Django 3.2.5 on 2021-07-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.CharField(default='🤍', max_length=5),
        ),
    ]
